config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :events do
    resources :participants, only: [:create, :destroy]
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  get "/dashboard", to: "pages#dashboard"
  get "/home", to: "pages#home"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/event.rb
class Event < ApplicationRecord
  include PgSearch::Model


  pg_search_scope :global_search,
  associated_against: {
    tags: [ :name ]
  }

  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user
  has_one :chatroom, dependent: :destroy
  has_many :participants, dependent: :destroy
  has_many :event_tags, dependent: :destroy
  has_many :tags, through: :event_tags

  accepts_nested_attributes_for :event_tags

  validates :name, :address, :start_date, :end_date, presence:true
  validates :max_people, numericality: { only_integer: true }
  validate :date_cannot_be_in_the_past, :end_date_cannot_be_before_start_date

  def end_date_cannot_be_before_start_date
    if start_date.present? && end_date.present? && end_date < start_date
      errors.add(:end_date, "can't be anterior at start date!")
    end
  end

  def date_cannot_be_in_the_past
    if start_date.present? && start_date < DateTime.now
      errors.add(:start_date, "can't be in the past!")
    end
  end

  def start_time
    self.start_date
  end

  def end_time
    self.end_date
  end

  def marker_class
    classes = []

    if public
      classes << 'public'
      classes << 'small-marker' if self.participants.count <= 9
      classes << 'medium-marker' if self.participants.count <= 19 && self.participants.count >= 10
      classes << 'large-marker' if self.participants.count <= 29 && self.participants.count >= 20
      classes << 'very-large-marker' if self.participants.count <= 39 && self.participants.count >= 30
      classes << 'big-marker' if self.participants.count <= 49 && self.participants.count >= 40
      classes << 'very-big-marker' if self.participants.count >= 50

    else
      classes << 'private'
      classes << 'small-marker' if self.participants.count <= 3
      classes << 'medium-marker' if self.participants.count <= 6 && self.participants.count >= 4
      classes << 'large-marker' if self.participants.count <= 11 && self.participants.count >= 7
      classes << 'very-large-marker' if self.participants.count <= 17 && self.participants.count >= 12
      classes << 'big-marker' if self.participants.count <= 25 && self.participants.count >= 18
      classes << 'very-big-marker' if self.participants.count >= 26

    end
    classes.join(' ')
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :index ]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
    if params[:query]
      @events = Event.global_search(params[:query])
    end

    @tags = Tag.all
    @markers = @events.geocoded.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { event: }),
        marker_html: render_to_string(partial: "marker", locals: { event: })
      }
    end
  end

  def show
    @markers =
    [
      {
        lat: @event.latitude,
        lng: @event.longitude,
        marker_html: render_to_string(partial: "marker", locals: { event: @event })
      }
    ]
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      tags = params[:event][:event_tag_ids]
      tags.shift
      tags.each do |tag|
        event_tag = EventTag.create!(event_id: @event.id, tag_id: tag.to_i)
      end

      participant = Participant.new(user_id: current_user.id, event_id: @event.id)
      participant.save
      chatroom = Chatroom.create!(name: @event.name, event_id: @event.id)
      redirect_to event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      EventTag.where(event_id: @event.id).each do |event_tag|
        event_tag.destroy
      end
      tags = params[:event][:event_tag_ids]
      tags.shift
      tags.each do |tag|
        event_tag = EventTag.create!(event_id: @event.id, tag_id: tag.to_i)
      end
      redirect_to event_path(@event)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, status: :see_other
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :start_date, :end_date, :description, :photo, :address, :public, :max_people, :event_tag_ids)
  end
end

app/views/events/_info_window.html.erb
<h5><%= event.name %></h5>
<p><%= event.address %></p>
<%= link_to "Voir l'évènement", event_path(event) %>

app/views/events/_marker.html.erb
<div data-controller="markerspulse" class="event-marker marker-animate<%= event.marker_class %>">
  <% if event.public %>
    <%= image_tag "markers/publiciconnearnow2.png" %>
  <% else %>
    <%= image_tag "markers/iconepriveenearnow2.png"%>
  <% end %>
</div>

app/views/events/edit.html.erb
<% if current_user == @event.user %>
  <div class="title-create">
    <h5>Modifier <%= @event.name %> <i class="fa-regular fa-compass"></i></h4>
  </div>
  <div class="container-heba form-color edit-form">
  <%= simple_form_for @event, class: "form-content"  do |f|%>
      <div class="top-space">
      <%= f.input :name, label: "Nom"%>
      </div>
      <%= f.input :description %>
      <%= f.input :address , label: "Adresse"%>
      <%= f.input :start_date, label: "Date de début",
        as: :string,
        input_html: { data: { controller: "datepicker", datepicker_date_value: @event.start_date } } %>
      <%= f.input :end_date, label: "Date de fin",
        as: :string,
        input_html: { data: { controller: "datepicker", datepicker_date_value: @event.end_date } } %>
      <%= f.input :public %>
      <%= f.input :max_people , label: "Maximum de participants"%>
      <%= f.input :event_tag_ids,
        collection: Tag.all,
        as: :check_boxes,
        required: true,
        input_html: { class: "tag-selector" },
        item_wrapper_class: 'form-tags',
        checked: @event.tags.map {|tag| tag.id }
      %>
      <div class="submit-button-formulaire">
      <%= f.submit class: "submit-btn", value: "Modifier"%>
      </div>
  </div>
  <% end %>
<% else %>
  <p>Vous ne pouvez pas modifier cet évènement!</p>
<% end %>

app/views/events/index.html.erb
<div class="body-container">
  <div class="banner">
    <h5>NearNow
    <i class="fa-regular fa-compass rotating boussole"></i>
    </h5>
  </div>

  <div class="mapbox-design"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
    data-map-page-value="index"
    data-map-user-location-value="<%= session[:event].nil? ? [5.3699525 ,43.2961743] : [session[:event]["longitude"], session[:event]["latitude"]] %>">
  <div class="index-tags-container">
    <div class="index-tags">
        <% if params[:query] %>
          <div class="index-tag">
            <%= form_with url: events_path, method: :get, class: "d-flex" do %>
              <%= submit_tag "Tous", class:"index-btn-tag"%>
            <% end %>
          </div>
        <% else %>
          <div class="index-tag">
            <%= form_with url: events_path, method: :get, class: "d-flex" do %>
              <%= submit_tag "Tous", class:"index-btn-tag-active"%>
            <% end %>
          </div>
        <% end %>
        <% @tags.each do |tag| %>
          <% if params[:query] == tag.name %>
            <div class="index-tag">
              <%= form_with url: events_path, method: :get, class: "d-flex" do %>
                <%= submit_tag tag.name, name: "query", class:"index-btn-tag-active" %>
              <% end %>
            </div>
          <% else %>
            <div class="index-tag">
                <%= form_with url: events_path, method: :get, class: "d-flex" do %>
                  <%= submit_tag tag.name, name: "query", class:"index-btn-tag" %>
                <% end %>
            </div>
          <% end %>
        <% end %>
    </div>
  </div>
  <% if user_signed_in? %>
    <div class="profile-page">
      <div class="profile-infos">
        <div class="username-photo">
          <%= image_tag "photo-toto.jpg", class: "homepage-photo" %>
        </div>

        <div class="username">
          <h5> @<%= current_user.username %></h5>
        </div>

      </div>

      <div class="profile-homepage-description">
        <p class="description-text"><%= current_user.description%></p>
        <p class="participation-text"><span class="embed-participation"><%= Participant.where(user_id: current_user.id).count %></span> participation(s) à des évènements</p>
      </div>

      <div class="profile-actions">
        <%= link_to "Calendrier", dashboard_path, class: "button-blueish" %>
        <%= link_to "Créer un évènement", new_event_path, class: "button-blueish" %>
      </div>

    </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="title-create">
  <h4>Créer un évènement <i class="fa-regular fa-compass rotating"></i></h4>

</div>

<div class="container-heba form-color" data-controller="toggle-maxpeople">
  <%= simple_form_for @event, class: "form-content" do |f| %>
    <div class="top-space">
      <%= f.input :name, label: "Nom" %>
    </div>
      <%= f.input :description, label: "Description" %>
      <%= f.input :address, label: "Adresse",
        input_html: {data: {address_autocomplete_target: "address"} , class: "d-none"},
        wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
      <%= f.input :photo, as: :file %>
      <%= f.input :start_date,
        as: :string,
        label: "Date de début",
        input_html: { data: { controller: "datepicker" } }%>
      <%= f.input :end_date,
        as: :string,
        label: "Date de fin",
        input_html: { data: { controller: "datepicker" } }%>
      <%= f.input :public , input_html:{ data: { action:"click->toggle-maxpeople#toggle" }}%>
      <%= f.input :max_people, label: "Maximum de participants", input_html: {value: '5', data: { toggle_maxpeople_target: "input"}}%>

      <div class="form-tags">
        <%= f.input :event_tag_ids,
          collection: Tag.all,
          as: :check_boxes,
          input_html: { class: "tag-selector" },
          item_wrapper_class: 'form-tags',
          required: true %>
      </div>

      <div class="submit-button-formulaire">
        <%= f.submit class: "submit-btn", value: "Créer" %>
      </div>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="body-container">
  <div class="banner">
    <h5>NearNow
      <i class="fa-regular fa-compass rotating"></i>
    </h5>
  </div>
  <% session[:event] = @event %>
  <div class="mapbox-design"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
    data-map-page-value="show"
    data-map-user-location-value="<%= session[:event].nil? ? [5.3699525 ,43.2961743] : [session[:event]["longitude"], session[:event]["latitude"]] %>">
  <div class="show-page-background"></div>
  <div class="show-page">
    <div class="show-event-title">
      <h3 class="bold-title"><%= @event.name %></h3>
      <div class="show-creator-address">
        <p>créé par @<span class="bold-title"><%= @event.user.username %></span> <br>
        <i class="fa-solid fa-location-dot"></i> <%= @event.address %></p>
      </div>
    </div>
  <div class="show-event-card">
    <div class="show-event-infos">
      <div class="show-event-tags">
        <% @event.tags.each do |tag| %>
        <div class="show-tag">
          <%= tag.name %>
        </div>
        <% end %>
      </div>
      <% if @event.public %>
        <p class="participants-count"> <span class="nb-participants-bold"><%= @event.participants.count %></span> participant(s)</p>
      <% else %>
        <p class="participants-count"><span class="nb-participants-bold"><%= @event.participants.count %></span> participant(s) / <%= @event.max_people %> max.</p>
      <% end %>
      <p class="show-start-date">Commence le <span class="datetime-show-start"><%= @event.start_date.strftime("%d/%m/%Y") %></span></p>
      <p class="show-start-time">A partir de <span class="datetime-show-start"><%= @event.start_date.strftime("%H:%M") %></span></p>
    </div>
    <% if @event.photo.attached? %>
      <%= cl_image_tag @event.photo.key, class: "cloudinary-show" %>
    <% end %>
  </div>

  <div class="show-description">
    <p><%= @event.description %></p>
  </div>

  <div class="show-actions-container">
  <% if current_user == @event.user %>
  <div class="show-actions">
    <%= link_to "Aller à la discussion", chatroom_path(@event.chatroom) %>
    <%= link_to "Éditer l'évènement", edit_event_path %>
    <%= link_to "Supprimer l'évènement", event_path(@event),
    data: {turbo_method: :delete, turbo_confirm: "Voulez-vous vraiment supprimer #{@event.name}?"} %>
  </div>

  <% else %>
    <% if Participant.where(user_id: current_user.id, event_id: @event.id).empty? %>
    <%# <p class="show-interest"><i class="interested?">Intéressé(e) ?</i></p> %>
    <div class="show-actions">
      <div class="button-blueish">
      <%= link_to "Ajouter au calendrier", event_participants_path(@event),
      data: {turbo_method: :post}, class:"show-cta"%>
        <i class="fa-solid fa-calendar"></i>
      </div>
    </div>
    <% else %>
    <div class="show-actions">
      <%= link_to "Aller à la discussion", chatroom_path(@event.chatroom) %>
      <%= link_to "Retirer du calendrier" ,  event_participant_path(@event),
      data: {turbo_method: :delete, turbo_confirm: "Voulez-vous vraiment retirer #{@event.name} de votre calendrier?"}%>
    </div>
    <% end %>
  <% end %>
  </div>
  </div>
  </div>
  </div>
</div>