config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :events do
    resources :participants, only: [:create, :destroy]
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  get "/dashboard", to: "pages#dashboard"
  get "/home", to: "pages#home"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/pages/dashboard.html.erb
<div class="body-container">
  <div class="dashboard-title">
    <h1>Dashboard <i class="fa-regular fa-compass rotating"></i></h1>
  </div>

  <div class="dashboard-wrapper">
    <div class="dashboard-synopsis">
      <p> <span class="greetings-dashboard">Hey <strong><%= current_user.username %></strong> !</span> <br>
      <span class="greetings-dashboard-paragraph">Prêt à sortir?</span></p>
    </div>
    <div class="dashb-events-created-container">
      <h3> Évènements créés</h3>
      <% if @events_created.empty? %>
       <p class="dashb-no-event-created"><i>Vous n'avez pas encore créé d'évènements !</i> <i class="fa-regular fa-face-rolling-eyes"></i></p>
      <% else %>
      <div class="dashb-events-created">
        <% @events_created.each do |event| %>
          <div class="dashb-event-created">
            <% if event.photo.attached? %>
              <%= link_to event_path(event) do %>
                <div class="dashb-event-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path event.photo.key %>')">
                  <%= event.name %>
                <% end %>
                </div>
            <% else %>
              <%= link_to event_path(event) do%>
                <div class="dashb-event-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">
                <%= event.name %>
                <% end %>
            </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <% end %>
      <h3>Évènements à venir</h3>
    </div>
    <div class="whole-calendar" data-controller="calendar-popup" data-calendar-popup-events-value="<%= @events.to_json%>">
      <%= month_calendar(events: @events) do |date, events| %>
        <h5> <%= date.day %> </h5>
        <% if events.count > 0 %>
          <i class="fa-solid fa-circle"></i>
        <% end %>
        <% events.each do |event| %>
          <div class="calendar-infobulle"
            data-action="click->calendar-popup#fire"
            data-calendar-popup-target="event"
            data-eventid="<%= event.id%>"
            data-eventName="<%= event.name %>"
            data-dayEvents="<%= events.to_json %>"
            data-eventDescription="<%= event.description %>"
            data-eventAddress="<%= event.address %>">
          </div>
        <% end %>
      <% end %>

      <div data-calendar-popup-target="eventpopup" class="event-popup">

      </div>
    </div>
  </div>

</div>

app/views/pages/home.html.erb
<div class="home-wrapper">

  <div class="accueil-wrapper-banner-boussole">
    <div class="homepage-banner-nearnow">
      <%= image_tag "greenbacknearnow-removebg-preview.png", class: "nearnow-banner-final" %>
    </div>

    <div class="boussole-homepage">
      <h5 class="title-home" id="title-homepage">
        <i class="fa-regular fa-compass rotating" id="boussole-homepage"></i>
      </h5>
    </div>
  </div>

  <div class="homepage-link">
    <%= link_to "Démarrer", events_path, class:"event-link-button" %>
  </div>
</div>